#!/bin/sh
# autopkgtest check: Build and run a program against libsdl2,to verify that the
# headers and pkg-config file are installed correctly
# Original work: (C) 2013 Canonical Ltd.
# Original author: Author: Vibhav Pant <vibhavp@ubuntu.com>
# Adaptations to libsdl2-dev: (C) 2018 Gianfranco Costamagna <locutusofborg@debian.org>

set -ex

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM

if [ -n "${DEB_HOST_GNU_TYPE:-}" ]; then
    cat <<EOF > "$WORKDIR/toolchain.cmake"
set(CMAKE_C_COMPILER $DEB_HOST_GNU_TYPE-gcc)
set(CMAKE_CXX_COMPILER $DEB_HOST_GNU_TYPE-g++)
set(PKG_CONFIG_EXECUTABLE $DEB_HOST_GNU_TYPE-pkg-config)
EOF
    CCFILE=-DCMAKE_TOOLCHAIN_FILE="$WORKDIR/toolchain.cmake"
else
    CCFILE=
fi

cp -R * $WORKDIR
cd $WORKDIR
mkdir build && cd build
cmake .. $CCFILE -DSDL_TEST=ON && make && make test
