#!/bin/sh
# This test emulates the assumption made by neverball_1.6.0+git20180603-2,
# which assumes that the CFLAGS from sdl2-config are enough to
# find related libraries like SDL2_ttf.
#
# Loosely based on glib2.0's debian/tests/build
# (C) 2012 Canonical Ltd.
# (C) 2018-2020 Simon McVittie
# Authors: Martin Pitt, Simon McVittie

set -eux

WORKDIR=$(mktemp -d)
trap 'rm -rf "$WORKDIR"' 0 INT QUIT ABRT PIPE TERM

if [ -n "${DEB_HOST_GNU_TYPE:-}" ]; then
    CROSS_COMPILE="$DEB_HOST_GNU_TYPE-"
else
    CROSS_COMPILE=
fi

cd "$WORKDIR"
cat <<EOF > use-sdl.c
#undef NDEBUG
#include <assert.h>

#include <SDL_ttf.h>

int main(void)
{
    const SDL_version *version = TTF_Linked_Version();
    assert (version != NULL);

    return 0;
}
EOF

for tool in pkg-config sdl2-config; do

    case "$tool" in
    (pkg-config)
        # shellcheck disable=SC2046
        "${CROSS_COMPILE}gcc" -o "use-${tool}" use-sdl.c $("${CROSS_COMPILE}pkg-config" --cflags --libs sdl2 SDL2_ttf)
        ;;
    (sdl2-config)
        # shellcheck disable=SC2046
        "${CROSS_COMPILE}gcc" -o "use-${tool}" use-sdl.c $(sdl2-config --cflags --libs) -lSDL2_ttf
        ;;
    (*)
        exit 1
        ;;
    esac

    echo "build (with $tool): OK"
    [ -x use-${tool} ]
    ./use-${tool}
    echo "run (with $tool): OK"
done
